config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: 'stores#index'

  get '/stores/searchstore',  to: 'stores#search_store'
  resources :stores do
    collection do
      get 'search'
    end
    resources :reviews do
      resources :comments, only: [:create, :destroy]
    end
  end
  resources :users
end

app/models/store.rb
class Store < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :store_type
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :vibe
  belongs_to_active_hash :bring
  belongs_to_active_hash :concent
  belongs_to_active_hash :alcohol
  belongs_to_active_hash :smoke
  belongs_to_active_hash :flavor_sale
  belongs_to_active_hash :wifi
  belongs_to_active_hash :card

  belongs_to :user
  has_many :reviews, dependent: :destroy

  def self.search(search)
    if search != ""
      Store.where('store_name LIKE(?)', "%#{search}%")
    else
      Store.all
    end
  end

  with_options presence: true do
    validates :store_name
    validates :postal_code
    validates :city
    validates :house_number
    validates :phone_number
    validates :access
  end

  validates :prefecture_id, numericality: { other_than: 1 }
end

app/models/store_type.rb
class StoreType < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'シーシャ専門店'},
    { id: 3, name: 'シーシャバー'},
    { id: 4, name: '飲食メイン'},
    { id: 5, name: 'その他'}
  ]

  include ActiveHash::Associations
  has_many :stores
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController

  before_action :create_searching_object,only: [:index,:search_store]

  def index
    @stores = Store.order("created_at DESC") 
    @results = @q.result(distinct: true)
  end

  def new
    @store = Store.new
  end
  
  def create
    @store = Store.new(store_params)
    if @store.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @store = Store.find(params[:id])
    @reviews = @store.reviews
  end

  def search_store
    @results = @q.result
  end

  def edit
    @store = Store.find(params[:id])
  end

  # def destroy
  #   store = Store.find(params[:id])
  #   store.destroy
  # end

private

  def store_params
    params.require(:store).permit(:store_name, :store_type_id, :postal_code, :prefecture_id, :city, :house_number, :phone_number, :building_name, :access, :home_page, :day_off, :opening_hours, :minimum_charge, :price_info, :vibe_id, :bring_id, :concent_id, :alcohol_id, :smoke_id, :flavor_sale_id, :wifi_id, :card_id, :additional_info).merge(user_id: current_user.id)
  end

  def create_searching_object
    @q = Store.ransack(params[:q])
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/edit.html.erb
<%= form_with(model: [@store], url: store_path, local: true) do |f| %>

  <%# <div class="review-box"> %>
    ストア情報を編集する
     <%= f.label :store_name %>
      <%= f.text_field :store_name, class:"flavor", placeholder:"店名" %>

      <%= f.label :store_type %>
      <%= f.collection_select(:store_type_id, StoreType.all, :id, :name, {}, {class:"companion-select"}) %>

      <%= f.label :postal_code %>
      <%= f.text_field :postal_code, class:"message", placeholder:"" %>

      <%= f.label :prefecture %>
      <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"companion-select"}) %>

      <%= f.label :city %>
      <%= f.text_field :city %>

       <%= f.label :house_number %>
      <%= f.text_field :house_number, class:"message", placeholder:"" %>

       <%= f.label :building_name %>
      <%= f.text_field :building_name, class:"message", placeholder:"" %>

       <%= f.label :phone_number %>
      <%= f.text_field :phone_number, class:"message", placeholder:"" %>

       <%= f.label :access %>
      <%= f.text_field :access, class:"message", placeholder:"" %>

       <%= f.label :home_page %>
      <%= f.text_field :home_page, class:"message", placeholder:"" %>

       <%= f.label :day_off %>
      <%= f.text_field :day_off, class:"message", placeholder:"" %>

       <%= f.label :opening_hours %>
      <%= f.text_field :opening_hours, class:"message", placeholder:"" %>

       <%= f.label :minimum_charge %>
      <%= f.text_field :minimum_charge, class:"message", placeholder:"" %>

       <%= f.label :price_info %>
      <%= f.text_area :price_info, class:"message", placeholder:"" %>

        <%= f.label :vibe %>
      <%= f.collection_select(:vibe_id, Vibe.all, :id, :name, {}, {class:"companion-select"}) %>

       <%= f.label :bring %>
      <%= f.collection_select(:bring_id, Bring.all, :id, :name, {}, {class:"companion-select"}) %>

       <%= f.label :concent %>
      <%= f.collection_select(:concent_id, Concent.all, :id, :name, {}, {class:"companion-select"}) %>

       <%= f.label :alcohol %>
      <%= f.collection_select(:alcohol_id, Alcohol.all, :id, :name, {}, {class:"companion-select"}) %>

       <%= f.label :smoke %>
      <%= f.collection_select(:smoke_id, Smoke.all, :id, :name, {}, {class:"companion-select"}) %>

       <%= f.label :flavor_sale %>
      <%= f.collection_select(:flavor_sale_id, FlavorSale.all, :id, :name, {}, {class:"companion-select"}) %>

       <%= f.label :wifi %>
      <%= f.collection_select(:wifi_id, Wifi.all, :id, :name, {}, {class:"companion-select"}) %>

       <%= f.label :card %>
      <%= f.collection_select(:card_id, Card.all, :id, :name, {}, {class:"companion-select"}) %>

      <%= f.label :additional_info %>
      <%= f.text_area :additional_info, class:"message", placeholder:"" %>

      <%= f.submit "変更する" ,class:"btn" %>
  <%# </div> %>
<% end %>

app/views/stores/index.html.erb
<%# 画面上部部分 %>
  <div class='title-contents'>
    <h2 class='service-title'>
      みんなのシーシャ活動アプリ
    </h2>
    <p class='service-explain'>
      IN TO SHISHAはみんなのシーシャ活動記録がシェアできる
    </p>
    <p class='service-explain'>
      シーシャ業界初のsnsアプリです
    </p>
    <div class='store-btn'>
      <%#= link_to image_tag("app/assets/images/app.png", class:"apple-btn"), "#" %>
      <%#= link_to image_tag("app/assets/images/google.png", class:"google-btn"), "#" %>
    </div>
  </div>

  <h1>店舗検索</h1>
  <%= search_form_for @q, url: stores_searchstore_path do |f| %>
    <%= f.label :store_name_cont, '店舗名(キーワード可)' %>
    <%= f.search_field :store_name_cont %>
    <br>
    <%= f.label :prefecture_id_eq, '都道府県検索' %>
        <%= f.collection_select(:prefecture_id_eq, Prefecture.all, :id, :name, {}, {class:"companion-select"}) %>
    <%= f.submit '検索' %>
  <% end %>

  <%# /画面上部部分  %>

<%# レビュー一覧表示 %>
<div class='review-contents'>
    <h2 class='title'>みんなの煙活一覧</h2>
    <%= link_to '新規投稿', new_store_path, class: "subtitle" %>
    <ul class='review-lists'>

    <% @stores.each do |store| %>
      <%= link_to store.store_name, store_path(store.id) %>
      <%= store.prefecture.name %>
      <%= store.city %>
      <%#= render partial: "shares/index" %>
    <% end %>

    <%# <% if @review.length == 0 %>
      <%# <li class='list'>
        <%= link_to '#' do %>
        <%# <%= image_tag "shisha.png", class: "shisha-img" %>
        <%# <div class='review-info'>
          <h3 class='review-name'>
            レビューを投稿してね！
          </h3>
          <div class='review-date'>
            <span>20XX-01-01<br></span>
            <div class='heart-btn'>
              <%= image_tag "heart.png", class:"heart-icon" %>
              <%# <span class='heart-count'>0</span>
            </div>
            
          </div>
        </div>
        <% end %>
      <%# </li>
    <% end%>

    </ul>
  </div>

</div>
<%= link_to( new_store_path,method: :get, class: 'review-btn') do %>
  <span class='review-btn-text'>店舗登録</span>
  <%= image_tag 'review-btn.png' , size: '185x50' ,class: "review-btn-icon" %>
<% end %>

<%# /レビュー一覧表示 %>

app/views/stores/new.html.erb
<%= form_with model: @store, url:stores_path, local: true do |f| %>

  <div class="store-review-box">
    店舗登録をする
    <div class="store-review-content">
      <%= f.label :store_name %>
      <%= f.text_field :store_name, class:"flavor", placeholder:"店名" %>

      <%= f.label :store_type %>
      <%= f.collection_select(:store_type_id, StoreType.all, :id, :name, {}, {class:"companion-select"}) %>

      <%= f.label :postal_code %>
      <%= f.text_field :postal_code, class:"message", placeholder:"" %>

      <%= f.label :prefecture %>
      <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"companion-select"}) %>

      <%= f.label :city %>
      <%= f.text_field :city %>

       <%= f.label :house_number %>
      <%= f.text_field :house_number, class:"message", placeholder:"" %>

       <%= f.label :building_name %>
      <%= f.text_field :building_name, class:"message", placeholder:"" %>

       <%= f.label :phone_number %>
      <%= f.text_field :phone_number, class:"message", placeholder:"" %>

       <%= f.label :access %>
      <%= f.text_field :access, class:"message", placeholder:"" %>

       <%= f.label :home_page %>
      <%= f.text_field :home_page, class:"message", placeholder:"" %>

       <%= f.label :day_off %>
      <%= f.text_field :day_off, class:"message", placeholder:"" %>

       <%= f.label :opening_hours %>
      <%= f.text_field :opening_hours, class:"message", placeholder:"" %>

       <%= f.label :minimum_charge %>
      <%= f.text_field :minimum_charge, class:"message", placeholder:"" %>

       <%= f.label :price_info %>
      <%= f.text_area :price_info, class:"message", placeholder:"" %>

        <%= f.label :vibe %>
      <%= f.collection_select(:vibe_id, Vibe.all, :id, :name, {}, {class:"companion-select"}) %>

       <%= f.label :bring %>
      <%= f.collection_select(:bring_id, Bring.all, :id, :name, {}, {class:"companion-select"}) %>

       <%= f.label :concent %>
      <%= f.collection_select(:concent_id, Concent.all, :id, :name, {}, {class:"companion-select"}) %>

       <%= f.label :alcohol %>
      <%= f.collection_select(:alcohol_id, Alcohol.all, :id, :name, {}, {class:"companion-select"}) %>

       <%= f.label :smoke %>
      <%= f.collection_select(:smoke_id, Smoke.all, :id, :name, {}, {class:"companion-select"}) %>

       <%= f.label :flavor_sale %>
      <%= f.collection_select(:flavor_sale_id, FlavorSale.all, :id, :name, {}, {class:"companion-select"}) %>

       <%= f.label :wifi %>
      <%= f.collection_select(:wifi_id, Wifi.all, :id, :name, {}, {class:"companion-select"}) %>

       <%= f.label :card %>
      <%= f.collection_select(:card_id, Card.all, :id, :name, {}, {class:"companion-select"}) %>

      <%= f.label :additional_info %>
      <%= f.text_area :additional_info, class:"message", placeholder:"" %>
      
      <%= f.submit "投稿する" ,class:"btn" %>
    </div>
  </div>
<% end %>

app/views/stores/search.html.erb
<h1>店舗検索</h1>
  <%= search_form_for @q, url: search_stores_path do |f| %>
    <%= f.label :store_name_cont, '店舗名(キーワード可)' %>
    <%= f.search_field :store_name_cont %>
    <br>
    <%= f.label :prefecture_cont, '都道府県検索' %>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"companion-select"}) %>
    <%= f.submit '検索' %>
  <% end %>
  
<div class="contents row">
  <% @stores.each do |store| %>
    <%= link_to store.store_name, store_path(store.id) %>
    <%= store.prefecture.name %>
    <%= store.city %>
    <%= store.day_off %>
    <%= store.opening_hours %>
  <% end %>
</div>

app/views/stores/search_store.html.erb
<h1>店舗検索</h1>
  <%= search_form_for @q, url: stores_searchstore_path do |f| %>
    <%= f.label :store_name_cont, '店舗名(キーワード可)' %>
    <%= f.search_field :store_name_cont %>
    <br>
    <%= f.label :prefecture_eq, '都道府県検索' %>
        <%= f.collection_select(:prefecture_id_eq, Prefecture.all, :id, :name, {}, {class:"companion-select"}) %>
    <%= f.submit '検索' %>
  <% end %>

<h1>検索結果</h1>
<% if @results.length !=0 %>

<div class="contents row">
  <% @results.each do |store| %>
    <%= link_to store.store_name, store_path(store.id) %>
    <%= store.prefecture.name %>
    <%= store.city %>
    <%= store.day_off %>
    <%= store.opening_hours %>
  <% end %>
  <% end %>
</div>

app/views/stores/show.html.erb
<%# 店舗の概要 %>
<div class="storereview--show">

    <div class="store-review-explain-box">
      <span><%= @store.store_name %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-review">投稿者</th>
          <td class="detail-value"><%= link_to @store.user.nickname, root_path %></td>
        </tr>
        <tr>
          <th class="detail-review">都道府県 / 市区町村</th>
          <td class="detail-value"><%= "#{@store.prefecture.name}/#{@store.city}" %></td>
        </tr>
        <tr>
          <th class="detail-review">店タイプ</th>
          <td class="detail-value"><%= @store.store_type.name %></td>
        </tr>

    ＜店舗詳細＞

    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-review"></th>
          <td class="detail-value"><%= @store.postal_code %></td>
        </tr>
        <tr>
          <th class="detail-review">住所</th>
          <td class="detail-value"><%= "#{@store.prefecture.name}#{@store.city}#{@store.house_number}" %></td>
        </tr>
        <tr>
          <th class="detail-review">店までのアクセス</th>
          <td class="detail-value"><%= @store.access %></td>
        </tr>
        <tr>
          <th class="detail-review">電話番号</th>
          <td class="detail-value"><%= @store.phone_number %></td>
        </tr>
        <tr>
          <th class="detail-review">ホームページ</th>
          <td class="detail-value"><%= @store.home_page %></td>
        </tr>
        <tr>
          <th class="detail-review">定休日</th>
          <td class="detail-value"><%= @store.day_off %></td>
        </tr>
        <tr>
          <th class="detail-review">営業時間</th>
          <td class="detail-value"><%= @store.opening_hours %></td>
        </tr>
        <tr>
          <th class="detail-review">最低料金</th>
          <td class="detail-value"><%= @store.minimum_charge %></td>
        </tr>
        <tr>
          <th class="detail-review">料金情報</th>
          <td class="detail-value"><%= @store.price_info %></td>
        </tr>

        ＜設備・ルール＞

        <tr>
          <th class="detail-review">店の雰囲気</th>
          <td class="detail-value"><%= @store.vibe.name %></td>
        </tr>
        <tr>
          <th class="detail-review">飲食物の持ち込み</th>
          <td class="detail-value"><%= @store.bring.name %></td>
        </tr>
        <tr>
          <th class="detail-review">コンセント</th>
          <td class="detail-value"><%= @store.concent.name %></td>
        </tr>
        <tr>
          <th class="detail-review">お酒</th>
          <td class="detail-value"><%= @store.alcohol.name %></td>
        </tr>
        <tr>
          <th class="detail-review">喫煙</th>
          <td class="detail-value"><%= @store.smoke.name %></td>
        </tr>
        <tr>
          <th class="detail-review">フレーバー販売</th>
          <td class="detail-value"><%= @store.flavor_sale.name %></td>
        </tr>
        <tr>
          <th class="detail-review">wifi環境</th>
          <td class="detail-value"><%= @store.wifi.name %></td>
        </tr>
        <tr>
          <th class="detail-review">カード決済</th>
          <td class="detail-value"><%= @store.card.name %></td>
        </tr>
        <tr>
          <th class="detail-review">補足情報</th>
          <td class="detail-value"><%= @store.additional_info %></td>
        </tr>
      </tbody>
    </table>

    <%= link_to 'この店舗のレビューをする', new_store_review_path(@store.id) %>

    ＜この店舗のレビュー＞
    <% @reviews.each do |review| %>
      <%#= render partial: "shares/index" %>
      <li class='list'>
        <div class='review-img-content'>
        <% if review.images.attached? %>
          <% review.images.each do |image| %>
          <%= image_tag image, class: "images" %>
          <% end %>
          <% end %>
        </div>
        <div class='review-info'>
          <%#<h3 class='review-name'>%>
            <%#= review.store.name %>
          <%#</h3>%>
          <div class='review-date'>
            <span><%= review.visit_date %></span>
          </div>
          <div class="review-flavor">
             <%= review.flavor %>
          </div>
          <div class="review-message">
             <%= review.message %>
          </div>

           <div class='review-check-btn'>
              <%= image_tag "heart.png", class:"heart-icon" %>
              <span class='heart-count'>0</span>
           </div>
          <%= link_to 'レビュー詳細', store_review_path(@store.id, review.id) %>
        </div>
     </li>
    <% end %>

       <ul class="more_list">
          <li>
            <%= link_to '編集', edit_store_path(@store.id), method: :get %>
          </li>
          <li>
            <%= link_to '削除', store_path(@store.id), method: :delete %>
          </li>
        </ul>
  
</div>