config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: 'stores#index'

  get '/stores/searchstore',  to: 'stores#search_store'
  resources :stores do
    collection do
      get 'search'
    end
    resources :reviews do
      resources :comments, only: [:create, :destroy]
    end
  end
  resources :users
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:new]

  def index
    @reviews = Review.order("created_at DESC")
  end

  def new
    @review = Review.new
  end
  
  def create
    binding.pry
    @review = Review.new(review_params)
    if @review.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @store = Store.find(params[:store_id])
    @review = Store.find(params[:store_id]).reviews.find(params[:id])
    @comment = Comment.new
    @comments = @review.comments.includes(:user).order("created_at DESC")
  end

  def edit
    @store = Store.find(params[:store_id])
    @review = Review.find(params[:id])
  end

   def update
    @store = Store.find(params[:store_id])
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to store_review_path(@store.id,@review.id)
    else
      render :edit
    end
  end

  def destroy
    @store = Store.find(params[:store_id])
    @review = Review.find(params[:id])
    if @review.destroy
      redirect_to root_path
     else
      render :show
     end
  end

  private

  def review_params
    params.require(:review).permit(:visit_date, :message, :flavor, :companion_id, :price, images: []).merge(user_id: current_user.id, store_id: params[:store_id])
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/edit.html.erb
<%= form_with(model: [@store, @review], url: store_review_path, local: true) do |f| %>

  <div class="review-box">
    レビューを編集する
    <div class="visit_date">
      <%= f.label :visit_date %>
      <%= f.date_select :visit_date, {use_month_numbers: true, start_year: 2000, end_year: Time.now.year}, {class:"visit"} %>
    </div>
    <div class="review-content">
      <%= f.label :flavor %>
      <%= f.text_field :flavor, class:"flavor", placeholder:"フレーバー" %>

      <%= f.label :price %>
      <%= f.text_field :price, class:"price", placeholder:"利用料金" %>

      <%= f.label :message %>
      <%= f.text_area :message, class:"message", placeholder:"テキスト" %>

      <%= f.label :companion %>
      <%= f.collection_select(:companion_id, Companion.all, :id, :name, {}, {class:"companion-select"}) %>

      <%= f.label :image %>
      <%= f.file_field :image %>

      <%= f.submit "変更する" ,class:"btn" %>
      <div id="image-list"></div>
    </div>
  </div>
<% end %>

app/views/reviews/index.html.erb
<%# 画面上部部分 %>
  <div class='title-contents'>
    <h2 class='service-title'>
      みんなのシーシャ活動アプリ
    </h2>
    <p class='service-explain'>
      IN TO SHISHAはみんなのシーシャ活動記録がシェアできる
    </p>
    <p class='service-explain'>
      シーシャ業界初のsnsアプリです
    </p>
    <div class='store-btn'>
      <%#= link_to image_tag("app/assets/images/app.png", class:"apple-btn"), "#" %>
      <%#= link_to image_tag("app/assets/images/google.png", class:"google-btn"), "#" %>
    </div>
  </div>
  <%# /画面上部部分  %>

<%# レビュー一覧表示 %>
<div class='review-contents'>
    <h2 class='title'>みんなの煙活一覧</h2>
    <%= link_to '新規投稿', "#", class: "subtitle" %>
    <ul class='review-lists'>

    <% @reviews.each do |review| %>
      <%= render partial: "shares/index" %>
    <% end %>

    <% if @reviews.length == 0 %>
      <li class='list'>
        <%= link_to '#' do %>
        <%= image_tag "shisha.png", class: "shisha-img" %>
        <div class='review-info'>
          <h3 class='review-name'>
            レビューを投稿してね！
          </h3>
          <div class='review-date'>
            <span>20XX-01-01<br></span>
            <div class='heart-btn'>
              <%= image_tag "heart.png", class:"heart-icon" %>
              <span class='heart-count'>0</span>
            </div>
            
          </div>
        </div>
        <% end %>
      </li>
    <% end%>

    </ul>
  </div>

</div>
<%= link_to( new_store_path,method: :get, class: 'review-btn') do %>
  <span class='review-btn-text'>店舗登録する</span>
  <%= image_tag 'review-btn.png' , size: '185x50' ,class: "review-btn-icon" %>
<% end %>

<%# /レビュー一覧表示 %>

app/views/reviews/new.html.erb
<%= form_with(model: [@store, @review], url: store_reviews_path, local: true) do |f| %>

  <div class="review-box">
    レビューを投稿する
    <div class="visit_date">
      <%= f.label :visit_date %>
      <%= f.date_select :visit_date, {use_month_numbers: true, start_year: 2000, end_year: Time.now.year}, {class:"visit"} %>
    </div>
    <div class="review-content">
      <%= f.label :flavor %>
      <%= f.text_field :flavor, class:"flavor", placeholder:"フレーバー" %>

      <%= f.label :price %>
      <%= f.text_field :price, class:"price", placeholder:"利用料金" %>

      <%= f.label :message %>
      <%= f.text_area :message, class:"message", placeholder:"テキスト" %>

      <%= f.label :companion %>
      <%= f.collection_select(:companion_id, Companion.all, :id, :name, {}, {class:"companion-select"}) %>

      <%= f.label :images %>
      <%= f.file_field :images, name: 'review[images][]', id: 'review_image', multiple: true %>

      <%= f.submit "投稿する" ,class:"btn" %>
      <div id="image-list"></div>
    </div>
  </div>
<% end %>

<% @review.images.each do |image| %>
  <%= image_tag image, class: 'images' %>
<% end %>

app/views/reviews/show.html.erb
<div class="review-show">
  <div class="review-box">
    
    <div class="review-price-box">
      <%# <span class="item-price">
       <%= @ %>
      <%#</span> %>
      <span class="review-postage">
        <%= @review.visit_date %>
      </span>
    </div>
    

    <div class="review-explain-box">
      <span><%= @review.message %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-review">レビュー者</th>
          <td class="detail-value"><%= link_to @review.user.nickname, root_path %></td>
        </tr>
        <tr>
          <th class="detail-review">利用料金</th>
          <td class="detail-value"><%= "¥#{@review.price}" %></td>
        </tr>
        <tr>
          <th class="detail-review">フレーバー</th>
          <td class="detail-value"><%= @review.flavor %></td>
        </tr>
        <tr>
          <th class="detail-review">同行者</th>
          <td class="detail-value"><%= @review.companion.name %></td>
        </tr>
      </tbody>
    </table>
    <div class="comment-content">
        <div class="review-img-content">
          <<div class="messages">
          <% @review.images.each do |image| %>
          <%= image_tag image, class:'images' %>
          <% end %>
         </div>
          <% if user_signed_in? %>
            <% if current_user.id == @review.user_id %>
            <ul class="more-list">
            <li>
              <%= link_to '編集', edit_store_review_path(@store.id, @review.id), method: :get, class: "item-red-btn" %>
            </li>
            /
            <li>
              <%= link_to '削除', store_review_path(@store.id, @review.id), method: :delete, class:"item-destroy" %>
            </li>
            </ul>
            <% end %>
        <% end %>
        </div>
      
          <%# <div class="coment-form">
            <% if user_signed_in? %>
              <%# <%= form_with(model: [@store, @review, @comment], url: store_review_comments_path, local: true) do |form| %> %>
                <%#= form.text_area :text, placeholder: "コメントする", rows: "2" %>
                <%#= form.submit "SEND" %>
              <%# end %>
            <%# else %>
              <%# <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong> %>
            <%# end %>
             <%# <div class="comments"> %>
              <%# <h4>＜コメント一覧＞</h4> %>
              <%# @comments.each do |comment| %>
               <%# <p> %>
              <%# <strong><%= link_to "@#{comment.user.nickname}", "/users/#{comment.user_id}" %>：</strong> %>
               <%#= comment.text %>
              <%# </p> %>
              <%# end %>
             <%# </div> %>
         <%# </div> %>
  </div>
    <div class="option">
      <div class="favorite-btn">
        <%= image_tag "heart.png" ,class:"favorite-icon" ,width:"20",height:"20"%>
        <span> 0</span>
      </div>
      
    </div>
  </div>
  

  
</div>