config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: 'stores#index'

  get '/stores/searchstore',  to: 'stores#search_store'
  resources :stores do
    collection do
      get 'search'
    end
    resources :reviews do
      resources :comments, only: [:create, :destroy]
    end
  end
  resources :users
end

app/models/alcohol.rb
class Alcohol < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '店内注文できる'},
    { id: 3, name: '持ち込みのみ可'},
    { id: 4, name: '店内アルコール禁止'},
    { id: 5, name: 'その他'}
  ]

  include ActiveHash::Associations
  has_many :stores
end

app/models/bring.rb
class Bring < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '持ち込み可(フード、アルコール、ソフトドリンク全て)'}, 
    { id: 3, name: '持ち込み可(フードのみ)'}, 
    { id: 4, name: '持ち込み可(フード・ソフトドリンクのみ)'},
    { id: 5, name: '持ち込み可(ソフトドリンクのみ)'},
    { id: 6, name: '持ち込み完全不可'},
    { id: 7, name: 'その他'}   
  ]

  include ActiveHash::Associations
  has_many :stores
end

app/models/card.rb
class Card < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '使用可能'}, 
    { id: 3, name: 'キャッシュのみ'}, 
    { id: 4, name: 'その他'}
  ]

  include ActiveHash::Associations
  has_many :stores
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :review

  validates :text, presence: true
end

app/models/companion.rb
class Companion < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    {id: 2, name: '一人で'},
    {id: 3, name: '友人と'},
    {id: 4, name: '仕事関係の方と'},
    {id: 5, name: '家族と'},
    {id: 6, name: '初対面の方と'},
    {id: 7, name: 'その他'}
  ]

  include ActiveHash::Associations
  has_many :reviews
end

app/models/concent.rb
class Concent < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'コンセント利用可'},
    { id: 3, name: 'コンセント利用不可'},
    { id: 4, name: 'その他'}
  ]

  include ActiveHash::Associations
  has_many :stores
end

app/models/flavor_sale.rb
class FlavorSale < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '店内で販売している'},
    { id: 3, name: '店内販売なし'},
    { id: 4, name: 'その他'}
  ]

  include ActiveHash::Associations
  has_many :stores
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    {id: 2, name: '北海道'}, {id: 3, name: '青森県'}, {id: 4, name: '岩手県'},
    {id: 5, name: '宮城県'}, {id: 6, name: '秋田県'}, {id: 7, name: '山形県'},
    {id: 8, name: '福島県'}, {id: 9, name: '茨城県'}, {id: 10, name: '栃木県'},
    {id: 11, name: '群馬県'}, {id: 12, name: '埼玉県'}, {id: 13, name: '千葉県'},
    {id: 14, name: '東京都'}, {id: 15, name: '神奈川県'}, {id: 16, name: '新潟県'},
    {id: 17, name: '富山県'}, {id: 18, name: '石川県'}, {id: 19, name: '福井県'},
    {id: 20, name: '山梨県'}, {id: 21, name: '長野県'}, {id: 22, name: '岐阜県'},
    {id: 23, name: '静岡県'}, {id: 24, name: '愛知県'}, {id: 25, name: '三重県'},
    {id: 26, name: '滋賀県'}, {id: 27, name: '京都府'}, {id: 28, name: '大阪府'},
    {id: 29, name: '兵庫県'}, {id: 30, name: '奈良県'}, {id: 31, name: '和歌山県'},
    {id: 32, name: '鳥取県'}, {id: 33, name: '島根県'}, {id: 34, name: '岡山県'},
    {id: 35, name: '広島県'}, {id: 36, name: '山口県'}, {id: 37, name: '徳島県'},
    {id: 38, name: '香川県'}, {id: 39, name: '愛媛県'}, {id: 40, name: '高知県'},
    {id: 41, name: '福岡県'}, {id: 42, name: '佐賀県'}, {id: 43, name: '長崎県'},
    {id: 44, name: '熊本県'}, {id: 45, name: '大分県'}, {id: 46, name: '宮崎県'},
    {id: 47, name: '鹿児島県'}, {id: 48, name: '沖縄県'}
  ]

  include ActiveHash::Associations
  has_many :stores
end

app/models/review.rb
class Review < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :companion
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many_attached :images
  belongs_to :store

  with_options presence: true do
    validates :visit_date
    validates :message
    validates :flavor
    validates :price, format: { with: /\A[0-9]+\z/ }
    validates :images
  end

  validates :companion_id, numericality: { other_than: 1 }
  
end

app/models/smoke.rb
class Smoke < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '喫煙可(紙タバコ・電子タバコ)'},
    { id: 3, name: '喫煙可(電子タバコのみ)'},
    { id: 4, name: '店内禁煙'},
    { id: 5, name: 'その他'}
  ]

  include ActiveHash::Associations
  has_many :stores
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/store.rb
class Store < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :store_type
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :vibe
  belongs_to_active_hash :bring
  belongs_to_active_hash :concent
  belongs_to_active_hash :alcohol
  belongs_to_active_hash :smoke
  belongs_to_active_hash :flavor_sale
  belongs_to_active_hash :wifi
  belongs_to_active_hash :card

  belongs_to :user
  has_many :reviews, dependent: :destroy

  def self.search(search)
    if search != ""
      Store.where('store_name LIKE(?)', "%#{search}%")
    else
      Store.all
    end
  end

  with_options presence: true do
    validates :store_name
    validates :postal_code
    validates :city
    validates :house_number
    validates :phone_number
    validates :access
  end

  validates :prefecture_id, numericality: { other_than: 1 }
end

app/models/store_type.rb
class StoreType < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'シーシャ専門店'},
    { id: 3, name: 'シーシャバー'},
    { id: 4, name: '飲食メイン'},
    { id: 5, name: 'その他'}
  ]

  include ActiveHash::Associations
  has_many :stores
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2, :line]

  with_options presence: true do
    validates :nickname
    validates :birth_date
    validates :password,format:{with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }
  end

  validates :profile, length: { maximum: 200 }

  has_many :sns_credentials
  has_many :reviews, dependent: :destroy
  has_many :stores, dependent: :destroy
  has_many :comments
  has_one_attached :image

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
        email: auth.info.email
    )

    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
end

app/models/vibe.rb
class Vibe < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '中東系'},
    { id: 3, name: 'アメリカン系'},
    { id: 4, name: '和風'},
    { id: 5, name: 'アジアン系'},
    { id: 6, name: 'ヨーロッパ系'},
    { id: 7, name: 'モダン系'},
    { id: 8, name: 'ポップ系'},
    { id: 9, name: 'ジャンク系'},
    { id: 10, name: 'ヴィンテージ系'},
    { id: 11, name: 'その他'}
  ]

  include ActiveHash::Associations
  has_many :stores
end

app/models/wifi.rb
class Wifi < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'フリーwifiあり'},
    { id: 3, name: 'フリーwifiなし'},
    { id: 4, name: 'その他'}
  ]

  include ActiveHash::Associations
  has_many :stores
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IN TO SHISHA</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
    <%= stylesheet_link_tag 'application', media: 'all'%>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">IN TO SHISHA</a></h1>
        <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
            <%= link_to "店舗登録", new_store_path, class: "post" %>
             <% if current_user.image.attached? %>
              <%= link_to image_tag(current_user.image, class: "mypage-show"), user_path(current_user.id) %>
            <% else %>
              <%= link_to image_tag("user.png", class: "mypage-show"), user_path(current_user.id) %>
            <% end %>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>
      </div>
    </header>
    <%= yield %>
    <footer>
      <p>
        Produced by elmo.
      </p>
    </footer>
  </body>
</html>

app/views/shares/_index.html.erb
 <li class='list'>
        <%= link_to store_review_path(@store.id) do %>
        <div class='review-img-content'>
          <%= image_tag review.image, class: "review-img" %>
      

        </div>
        <div class='review-info'>
          <%#<h3 class='review-name'>%>
            <%#= review.store.name %>
          <%#</h3>%>
          <div class='review-date'>
            <span><%= review.visit_date %></span>
           
          <div class="review-flavor">
             <%= review.flavor %>
          </div>
          <div class="review-message">
             <%= review.message %>
          </div>

           <div class='review-check-btn'>
              <%= image_tag "heart.png", class:"heart-icon" %>
              <span class='heart-count'>0</span>
              <%= link_to root_path do %>
              <%= image_tag "comment.png" ,class:"comment-icon" %>
              <% end %>
            </div>
          </div>
        </div>
        <% end %>
 </li>